# Generated by Django 3.0.6 on 2020-06-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('item_property', models.CharField(blank=True, choices=[('Countable', 'Countable'), ('Non-countable', 'Non-countable'), ('', 'default')], default='', max_length=25)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('opening_stock', models.CharField(blank=True, default='', max_length=100)),
                ('sku_code', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=100)),
                ('stock_type', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('net_cost', models.CharField(blank=True, default='', max_length=100)),
                ('vat', models.CharField(blank=True, default='', max_length=100)),
                ('vendor', models.CharField(blank=True, default='', max_length=100)),
                ('non_purchae', models.CharField(blank=True, default='', max_length=100)),
                ('sku_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ItemCategories')),
            ],
        ),
        migrations.AddField(
            model_name='itemcategories',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ItemGroup'),
        ),
    ]
