# Generated by Django 3.0.6 on 2020-06-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategories',
            name='item_property',
            field=models.CharField(blank=True, choices=[('Countable', 'Countable'), ('Non-countable', 'Non-countable'), ('', 'default')], default='', max_length=25),
        ),
    ]
