# Generated by Django 3.0.6 on 2020-06-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_auto_20200630_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategories',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.ItemGroup'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sku_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.ItemCategories'),
        ),
    ]
