# Generated by Django 3.0.6 on 2020-06-30 19:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('mobile1', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('pan_no', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=100)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), size=10), size=10)),
                ('qty', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), size=10), size=10)),
                ('price', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), size=10), size=10)),
                ('total', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), size=10), size=10)),
                ('vendor_contact1', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_contact2', models.CharField(blank=True, default='', max_length=100)),
                ('order_date', models.CharField(blank=True, default='', max_length=100)),
                ('order_status', models.CharField(blank=True, default='', max_length=100)),
                ('sub_total', models.CharField(blank=True, default='', max_length=100)),
                ('tax', models.CharField(blank=True, default='', max_length=100)),
                ('tax_amount', models.CharField(blank=True, default='', max_length=100)),
                ('total_amount', models.CharField(blank=True, default='', max_length=100)),
                ('remark', models.CharField(blank=True, default='', max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Vendor')),
            ],
        ),
    ]
