# Generated by Django 3.0.6 on 2020-06-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('mobile1', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('pan_no', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=100)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
