# Generated by Django 3.0.6 on 2020-06-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='purchase_order',
            old_name='venders',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='purchase_order',
            old_name='venders_contact1',
            new_name='vendor_contact1',
        ),
        migrations.RenameField(
            model_name='purchase_order',
            old_name='venders_contact2',
            new_name='vendor_contact2',
        ),
    ]
