# Generated by Django 3.0.6 on 2020-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('profile_image', models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=25)),
                ('phone_number', models.CharField(blank=True, default='', max_length=12)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=12)),
                ('email', models.CharField(blank=True, default='', max_length=500)),
                ('job_position', models.CharField(blank=True, default='', max_length=12)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('pan_no', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=100)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
