# Generated by Django 3.0.6 on 2020-06-29 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='', max_length=100)),
                ('representative', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('landmark', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('contact', models.CharField(blank=True, default='', max_length=100)),
                ('contact2', models.CharField(blank=True, default='', max_length=100)),
                ('service', models.CharField(blank=True, choices=[('Installation', 'Installation'), ('Service/Repair', 'Service/Repair'), ('', 'default')], default='', max_length=25)),
                ('problem', models.CharField(blank=True, default='', max_length=100)),
                ('assign_to', models.CharField(blank=True, default='', max_length=100)),
                ('service_report', models.CharField(blank=True, default='', max_length=100)),
                ('bill_no', models.CharField(blank=True, default='', max_length=100)),
                ('bill_amount', models.CharField(blank=True, default='', max_length=100)),
                ('bill_submit', models.CharField(blank=True, default='', max_length=100)),
                ('amount_received', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
