# Generated by Django 3.0.6 on 2020-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0002_remove_dailyworkreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
