# Generated by Django 3.0.6 on 2020-06-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0003_dailyworkreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
